---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  workspace: gitlab-my-apps-ws
  tenant: tetrate
  name: tetrate-demo-ingress-gw
  group: blog-test-gw-group
spec:
  workloadSelector:
    namespace: tetrate-demo
    labels:
      app: tsb-gateway-tetrate-demo
      istio: ingressgateway
  http:
  - name: demoapp
    port: 80
    hostname: tetrate-app.cx.tetrate.info
    routing:
      rules:
      - route:
          host: tetrate-demo/tetrate-app.tetrate-demo.svc.cluster.local
          port: 80
